#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Get version from argument, default to 1.0.0 if not provided
VERSION=${1:-1.0.0}

echo "Starting build process for version $VERSION..."

# 1. Run npm run build
echo "Running npm run build..."
npm run build

# 2. Run npm run build:legacy
echo "Running npm run build:legacy..."
npm run build:legacy

# 3. Rename license file
echo "Renaming license file..."
if [ -f "build/admin-legacy.js.LICENSE.txt" ]; then
    mv build/admin-legacy.js.LICENSE.txt build/admin.js.LICENSE.txt
    echo "Renamed build/admin-legacy.js.LICENSE.txt to build/admin.js.LICENSE.txt"
else
    echo "Warning: build/admin-legacy.js.LICENSE.txt not found. Skipping rename."
fi

# 4. Add headers
HEADER="/*
 * WPAB Boilerplate
 * Copyright (c) $(date +%Y) WP Anchor Bay - https://wpanchorbay.com
 *
 * This software is licensed under the GPLv2 or later.
 * This file is generated from un-compiled source code. Do not edit this file directly.
 *
 * For license information please see admin.js.LICENSE.txt
 */"

# List of files to edit
FILES=("build/admin.js" "build/admin-legacy.js")

# Loop through each file and prepend the header
for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "Adding header to $file..."
        echo "$HEADER" | cat - "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
        echo "Successfully added header to $file"
    else
        echo "Warning: File $file not found."
    fi
done

echo "Build and header addition complete for version $VERSION."
